### PR TITLE
Add support for Rails 7.2

### PR DESCRIPTION
**Pull request by n-rodriguez**
Thank you!

### CODE REVIEW

**Comment by n-rodriguez** [comment]
CI is green https://github.com/n-rodriguez/page_title_helper/actions/runs/10336525899

**Review by oliverklee — APPROVED** [review]
Looks good. Thanks! :heart:

**Comment by oliverklee** [comment]
@n-rodriguez I've just released version 8.0.0 with your changes:
https://github.com/lwe/page_title_helper/releases/tag/v8.0.0

Thank you again for contributing! :pray:

**Comment by n-rodriguez** [comment]
@oliverklee thank you!

**Pull request merged**
