### PR TITLE
[TASK] Add Ruby 2.3.0 to the build matrix

### PR DESCRIPTION
**Pull request by oliverklee**

### CODE REVIEW

**Comment by lwe** [comment]
Thanks, maybe we should just check rails 4.2 for Ruby 2.3, or what do you think?

**Comment by oliverklee** [comment]
I think we should check as many Ruby/Rails version combinations as possible to catch as many potential problems as possible. (In addition, the concept of the build matrix is to check every version of X with every version of Y, and to mark some combinations as "allowed failures". So there is no option of only checking Rails 4.2 with Ruby 2.3 AFAIK.)

**Comment by lwe** [comment]
ah nevermind, sorry for the confusion... :+1:

**Comment by lwe** [comment]
muchos gracias

**Pull request merged**
