### PR TITLE
[BUGFIX] Get the tests to run in Rails 4.2 and 5.0

### PR DESCRIPTION
**Pull request by oliverklee**
This PR currently only exists to see the results of the Travis build.

### CODE REVIEW

**Comment by oliverklee** [comment]
@lwe Any idea why the tests do not fail here (i.e., most probably are not executed at all)? (I've added a test that should fail as it asserts that 1 is equals to 2.)

**Comment by lwe** [comment]
I suspect it's an incompatibility with shoulda, however I'm very very open to simply get rid of shoulda and use plain old test/unit / ActiveSupport::TestCase.

**Comment by lwe** [comment]
...or try to require `require 'minitest/autorun'`?

**Comment by lwe** [comment]
^^ jup the autorun seems to do the trick for me (sorry, for the spamming)

**Comment by oliverklee** [comment]
This also works for me. Thanks!

Then I'll take care of getting the tests to run.

**Comment by lwe** [comment]
👍 you are welcome and thanks for getting the specs up to date.

PS: I would be open to get rid of shoulda and appraisals and simply use what minitest, respectively travis offers out of the box.

**Comment by oliverklee** [comment]
Appraisals is necessary to test with different Rails versions. (That's why I added it.)

I prefer RSpec for testing. I'll take care of converting the tests to RSpec. That will happen in a separate PR, though, as I prefer to have "one PR (and one commit) per issue".

**Comment by lwe** [comment]
RSpec also works for me 👍

It's possible to test against multiple Rails versions without appraisals, will create a PR for this myself.

**Comment by oliverklee** [comment]
The current failures depend on the order of the tests. I'm currently investigating this.

**Comment by oliverklee** [comment]
This PR finally is ready for review!

**Pull request merged**
