### PR TITLE
[TASK] Cleanup and improve the RuboCop configuration

### PR DESCRIPTION
**Pull request by oliverklee**
- call RuboCop with the --rails option to add Rails-specific cops
- put the open RobuCops to-dos in .rubocop_todo.yml and include it
  from the main RuboCop configuration (as recommended by RuboCop)
- use Rails-style indentation style settings

### CODE REVIEW

**Comment by lwe** [comment]
Agree with the `--rails` change, but what is the advantage of having the _todo AND other rubocop file? Why not simply add TODO or FIXME comments within the main rubocop configuration for things we'd like to improve or get down to a specific level? E.g.

```yaml
# TODO: reduce to a maximum of 12
Metrics/AbcSize:
  Max: 23
```

**Comment by oliverklee** [comment]
There are several reasons why I'd like to have this separation (and with these exact file names):

1. the rubocop_todo.yml will get auto-generated if rubocop is run with the --auto-gen-config option (see https://rubocop.readthedocs.io/en/latest/basic_usage/ ). This allows us to conveniently rework this file once we've cleaned up some violations.
2. Having these two files allows us to separate between "things we currently don't want to change, and general RuboCop settings" in .rubocop.yml and "things we'd like to work on and clean them up" in rubocop_todo.yml.
3. This is the structure that the RuboCop documentation recommends.

**Comment by oliverklee** [comment]
I'll update this PR now that the Appraisals PR is merged. Hold on …

**Comment by oliverklee** [comment]
Rebased.

**Pull request merged**
