### PR TITLE
[TASK] Add a list of maintainers to the README

### PR DESCRIPTION
**Pull request by oliverklee**

### CODE REVIEW

**Comment by oliverklee** [comment]
@lwe I've put you as first maintainer, and me second. Is this okay, or would you prefer the other way round?

**Comment by lwe** [comment]
I'd propose to order alphabetically by the GH Username:

```markdown
* @lwe - Lukas Westermann
* @oliverklee - Oliver Klee
```

**Comment by oliverklee** [comment]
done

**Comment by lwe** [comment]
Perfetto, thanks!

**Pull request merged**
