### PR TITLE
[CLEANUP] Fix the casing up the version-specific gemfiles

### PR DESCRIPTION
**Pull request by oliverklee**

### CODE REVIEW

**Comment by lwe** [comment]
Could you rebase, otherwise looks good to me. Thanks.

**Comment by lwe** [comment]
(Sorry, deleted my previous comment)

Don't think it's reasonable to change the upcasing, because _Gemfile_ itself is also upper-case, I think this is mainly a wrong default by rubocop and we should ignore casing rules for Gemfile* IMO.

**Comment by oliverklee** [comment]
Done.

**Comment by oliverklee** [comment]
Strange … I'll investigate the failures.

**Comment by lwe** [comment]
Ahhh, this is why we included the explicit versions in the execution of Rubocop, otherwise it also examines .lock files. Can these be globally ignored maybe?

**Comment by lwe** [comment]
or maybe it's better to simply rename to rails-4-2.gemfile or smth, then it can easily be run on *.gemfile? (i suppose we even discussed this once, but I opposed it, sorry 😄)

**Comment by oliverklee** [comment]
I've just undone the changes to the RuboCop call. Hopefully, the build should now pass.

**Comment by lwe** [comment]
:tada: thanks

**Pull request merged**
