### PR TITLE
[TASK] Update the Ruby versions for Travis CI

### PR DESCRIPTION
**Pull request by oliverklee**

### CODE REVIEW

**Comment by lwe** [comment]
Are tiny version numbers required? When specifying simply:

- 2.2
- 2.3
- 2.4

what does RVM do? Does it even work? Do they choose the latest tiny version.

Reason I'm asking is, because that way we as a project don't need to keep track of tiny ruby upgrades.

**Comment by oliverklee** [comment]
If I read this correctly, "2.x" will always point to the latest 2.x.y (starting with Ruby 2.1.0). I'm giving this a try.

**Comment by oliverklee** [comment]
At least for 2.4, this does not work. And for 2.2., it looks like the installed Ruby version 2.2.0p0 is too low for Rails 5.0 (which requires Ruby >= 2.2.2).

**Comment by oliverklee** [comment]
"2.3" does not work, either.

**Comment by oliverklee** [comment]
So it looks like 2.1 is the only version where we can do without a teeny version number.

**Comment by lwe** [comment]
Too bad, thanks for trying 👍

**Pull request merged**
