### PR TITLE
[TASK] Prepare the 4.0.0 release

### PR DESCRIPTION
**Pull request by oliverklee**
Also split up the changelog between the 3.0.0 and 4.0.0 changes (which
accidentally got lumped together).

### CODE REVIEW

**Comment by oliverklee** [comment]
@lwe ping

**Comment by nplusp** [comment]
It would be great to have it merged 🙃

**Comment by lwe** [comment]
Sorry, y'all pretty busy at *dayjob, however, @oliverklee - feel free to simply also merge it.

**Comment by oliverklee** [comment]
@lwe Thanks for the review and the merge!

Could you also please release the new version 4.0.0? Thanks!

**Comment by lwe** [comment]
@nplusp, version 4.0 is now on rubygems.

**Pull request merged**
